### ISSUE TITLE
来电挂断 插件 不会正常工作。

### ISSUE THREAD

**Issue by pbwind** [xdtianyu/CallerInfo#123]
*感谢您对【来电信息】应用的反馈*
*如果您正在提交一个 BUG，请按照模板填写信息。*
*如果您正在提交一个功能请求，请填写使用情景以便我们获取必要的信息*

#### 应用版本: 
2.5.2
#### 系统版本: 
8.1  6月份补丁
#### 手机品牌及型号:
nexus 6p 
#### 预置条件:
自动挂断
黑名单：
挂断关键字：诈骗 广告 中介 房 骚扰 中介 推销
临时禁用自动挂断（号码在24小时内多次来电时临时禁止自动挂断功能）
允许 显示在其他应用的上层
来电信息、来电信息插件，  电池未优化
#### 复现步骤:
1.接到骚扰电话，来电显示无浮窗。 响铃20S，不会自动挂断
2.结束通话后，到来电显示 主界面，来电号码已被软件标记为骚扰

#### 期望结果:
如果APP判断该电话是属于骚扰电话，符合挂断标准，应该在接到电话后，自行挂断电话

#### 实际结果:
并不会挂断来电。

**Comment by xdtianyu** [comment]
请试一下 https://github.com/xdtianyu/CallerInfo/releases/tag/v2.5.3 版本中的插件，谢谢

**Comment by luoluomeng** [comment]
debug看了一下，Android8下抛异常提示没有android.permission.MODIFY_PHONE_STATE权限
应该是需要设为系统默认电话应用才能生效
logcat如下：
TelecomService: : endCall: calls from pid = 15527: TSI.eC@EzU
08-17 09:45:43.905 15527 15544 W System.err: java.lang.SecurityException: Neither user 10176 nor current process has android.permission.MODIFY_PHONE_STATE.
08-17 09:45:43.905 15527 15544 W System.err:    at android.os.Parcel.readException(Parcel.java:1942)
08-17 09:45:43.905 15527 15544 W System.err:    at android.os.Parcel.readException(Parcel.java:1888)
08-17 09:45:43.905 16024 16024 I Dialer  : StatusBarNotifier.buildAndSendNotification - displaying notification for 2
08-17 09:45:43.906 15527 15544 W System.err:    at com.android.internal.telecom.ITelecomService$Stub$Proxy.endCall(ITelecomService.java:1343)
08-17 09:45:43.906 15527 15544 W System.err:    at android.telecom.TelecomManager.endCall(TelecomManager.java:1256)
08-17 09:45:43.906 15527 15544 W System.err:    at org.xdty.callerinfo.plugin.PluginService.tryEndCall(PluginService.java:316)
08-17 09:45:43.906 15527 15544 W System.err:    at org.xdty.callerinfo.plugin.PluginService.killPhoneCall(PluginService.java:269)
08-17 09:45:43.907 15527 15544 W System.err:    at org.xdty.callerinfo.plugin.PluginService.access$100(PluginService.java:28)
08-17 09:45:43.907 15527 15544 W System.err:    at org.xdty.callerinfo.plugin.PluginService$1.hangUpPhoneCall(PluginService.java:80)
08-17 09:45:43.907 15527 15544 W System.err:    at org.xdty.callerinfo.plugin.IPluginService$Stub.onTransact(IPluginService.java:62)
08-17 09:45:43.907 15527 15544 W System.err:    at android.os.Binder.execTransact(Binder.java:674)
