### ISSUE TITLE
不能绑定伪GoogleService(MicoG)服务，打开会FC

### ISSUE THREAD

**Issue by qqzwc** [xdtianyu/CallerInfo#132]
*感谢您对【来电信息】应用的反馈*
*如果您正在提交一个 BUG，请按照模板填写信息。*
*如果您正在提交一个功能请求，请填写使用情景以便我们获取必要的信息*

#### 复现步骤:
1.安装microg (https://microg.org/ , GmsCore和GsfProxy) 
2.打开软件，无法启动，FC

#### 期望结果:
应用正常打开[不要监听或者可选监听绑定Google C2DM消息]。
#### 实际结果:
E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
E AndroidRuntime: Process: org.xdty.callerinfo, PID: 2848
E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:29)
E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:6)
E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:13)
E AndroidRuntime: 	at com.google.firebase.iid.zzx.zzb(Unknown Source:85)
E AndroidRuntime: 	at com.google.firebase.iid.zzv.zza(Unknown Source:48)
E AndroidRuntime: 	at com.google.firebase.iid.zzv.zzb(Unknown Source:10)
E AndroidRuntime: 	at com.google.firebase.iid.zzan.zzc(Unknown Source:18)
E AndroidRuntime: 	at com.google.firebase.iid.zzo.zza(Unknown Source:2)
E AndroidRuntime: 	at com.google.firebase.iid.zzp.run(Unknown Source:6)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

**Comment by qqzwc** [comment]
清空数据，卸载APP再重新安装后，目测故障消失（没有再FC）
但是似乎数据显示是延迟的，来电话的时候，没有来电信息，我点接听的时候，信息才出来。。。
