### ISSUE TITLE
来电信息2.3.0在Android 8.1上结束通话后崩溃

### ISSUE THREAD

**Issue by chenshaoju** [xdtianyu/CallerInfo#99]
Android版本：8.1.0
OS版本：LineageOS 15.1 20180416
来电信息版本：2.3.0
设备：OnePlus 5T

操作步骤：接听电话后挂断，出现来电信息已停止工作的提示。

Logcat日志：
```
--------- beginning of crash
04-17 18:43:54.867 31600 31600 E AndroidRuntime: FATAL EXCEPTION: main
04-17 18:43:54.867 31600 31600 E AndroidRuntime: Process: org.xdty.callerinfo, PID: 31600
04-17 18:43:54.867 31600 31600 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.xdty.callerinfo/org.xdty.callerinfo.activity.MarkActivity}: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7c1de -- permission denied for window type 2003
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7c1de -- permission denied for window type 2003
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:330)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at org.xdty.callerinfo.activity.MarkActivity.showAlertDialog(MarkActivity.java:120)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at org.xdty.callerinfo.activity.MarkActivity.onResume(MarkActivity.java:62)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7107)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
04-17 18:43:54.867 31600 31600 E AndroidRuntime: 	... 10 more
04-17 18:43:54.867  2549  2697 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
04-17 18:43:54.868  2549  2549 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
04-17 18:43:54.869  1300  2821 W ActivityManager:   Force finishing activity org.xdty.callerinfo/.activity.MarkActivity
04-17 18:43:54.871  1300  2821 W ActivityManager:   Force finishing activity com.android.dialer/com.android.incallui.InCallActivity
04-17 18:43:54.893  1300  1332 I ActivityManager: Showing crash dialog for package org.xdty.callerinfo u0
```

内置的错误捕获日志：
```
Build version: 2.3.0 
Build date: 1979-11-30 00:00:00 
Current date: 2018-04-17 18:51:38 
Device: OnePlus ONEPLUS A5010 
 
Stack trace:  
java.lang.RuntimeException: Unable to resume activity {org.xdty.callerinfo/org.xdty.callerinfo.activity.MarkActivity}: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@d1cdfd8 -- permission denied for window type 2003
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@d1cdfd8 -- permission denied for window type 2003
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.app.Dialog.show(Dialog.java:330)
	at org.xdty.callerinfo.activity.MarkActivity.showAlertDialog(MarkActivity.java:120)
	at org.xdty.callerinfo.activity.MarkActivity.onResume(MarkActivity.java:62)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7107)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
	... 10 more
```

**Comment by chenshaoju** [comment]
此问题和 https://github.com/xdtianyu/CallerInfo/issues/76 类似，暂时关闭，请跳转到原有Issue了解详情。
